# Generated by Django 3.0.3 on 2020-06-06 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Mr_N0_0NEApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='search',
            options={'verbose_name_plural': 'Searches'},
        ),
    ]
